# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glane < Formula
  desc "Full-text and semantic search over your saved tech-watch posts"
  homepage "https://github.com/jcgay/glane"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcgay/glane/releases/download/v1.0.0/glane_1.0.0_darwin_amd64.tar.gz"
      sha256 "914f11d5dbb51963d716857efd32e7b9c7d62cdecf0f473a774eb29ce65c000a"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcgay/glane/releases/download/v1.0.0/glane_1.0.0_darwin_arm64.tar.gz"
      sha256 "43932eb614fe68da1953b8de91a899f1ba687b39906bfd46022c47428e95b8a9"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.0.0/glane_1.0.0_linux_amd64.tar.gz"
      sha256 "841050784e1a8f93de1a85d7cdb0e5de09ce27158ec16fd089bf7e3b79054847"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.0.0/glane_1.0.0_linux_arm64.tar.gz"
      sha256 "599cdeaf7863ead3a333ac2cd3cd2a3765e7af17cb325f02976be998efb27749"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To let Claude Code search your tech-watch, register the plugin:
        claude plugin marketplace add jcgay/glane
        claude plugin install glane@glane
    EOS
  end
end
