# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glane < Formula
  desc "Full-text and semantic search over your saved tech-watch posts"
  homepage "https://github.com/jcgay/glane"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcgay/glane/releases/download/v1.1.1/glane_1.1.1_darwin_amd64.tar.gz"
      sha256 "0a7c1301fb42f79456202b1bfe3d5554119f8c1932ed7c842f07a1cc9334dfd2"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcgay/glane/releases/download/v1.1.1/glane_1.1.1_darwin_arm64.tar.gz"
      sha256 "d8c54f408464150106fa9adc26db41c0b2f6caed284f3246bfee093e85374285"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.1.1/glane_1.1.1_linux_amd64.tar.gz"
      sha256 "99c788cee4987bed677eafd1dd32945ae151b05209eba2ef48e62b45460d83bc"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.1.1/glane_1.1.1_linux_arm64.tar.gz"
      sha256 "273b241ceeb4ec567704ec6da1d5bd6745409791d413f09a6f48728d3068f668"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To let Claude Code search your tech-watch, register the plugin:
        claude plugin marketplace add jcgay/glane
        claude plugin install glane@glane
    EOS
  end
end
