# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glane < Formula
  desc "Full-text and semantic search over your saved tech-watch posts"
  homepage "https://github.com/jcgay/glane"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcgay/glane/releases/download/v1.2.0/glane_1.2.0_darwin_amd64.tar.gz"
      sha256 "ad72590f92a8a717c59eaa5a026b01e87b236b952c13698cdc393014d66f3716"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcgay/glane/releases/download/v1.2.0/glane_1.2.0_darwin_arm64.tar.gz"
      sha256 "3b17ab116fe4ff3c209ae3141cf2d1331516b9ff287b4e26238111ec52ed779c"

      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.2.0/glane_1.2.0_linux_amd64.tar.gz"
      sha256 "122316875b9a96366edbcea0ab496bcf39a680033d202763e3e2caa44d546735"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/glane/releases/download/v1.2.0/glane_1.2.0_linux_arm64.tar.gz"
      sha256 "450ba8067ccfb006ba560a993752c2d88f9d351368b94da890c73e0d0cbf3975"
      define_method(:install) do
        bin.install "glane"
        fish_completion.install "completions/glane.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To let Claude Code search your tech-watch, register the plugin:
        claude plugin marketplace add jcgay/glane
        claude plugin install glane@glane
    EOS
  end
end
