# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ParallelGitRepo < Formula
  desc "Run command on git repositories in parallel."
  homepage "https://github.com/jcgay/parallel-git-repo"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v1.1.1/parallel-git-repo_1.1.1_darwin_amd64.tar.gz"
      sha256 "93b8cfe70db4aea7825397bcd7746c0f34302f9bc522cf10ffd41e0785e5d7e7"

      define_method(:install) do
        bin.install "parallel-git-repo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v1.1.1/parallel-git-repo_1.1.1_darwin_arm64.tar.gz"
      sha256 "811b1243a8eb8752c331b0c13472638fafa4ead00f0edd8d0c3177418e08dd4a"

      define_method(:install) do
        bin.install "parallel-git-repo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v1.1.1/parallel-git-repo_1.1.1_linux_amd64.tar.gz"
      sha256 "a466e30b52703d611323485abad11836b518c09972b5ceedd09061468eff5302"
      define_method(:install) do
        bin.install "parallel-git-repo"
      end
    end
  end
end
