# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SocialTimeline < Formula
  desc "Fetch Bluesky and Mastodon home timelines as Markdown"
  homepage "https://github.com/jcgay/social-timeline"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcgay/social-timeline/releases/download/v1.0.1/social-timeline_darwin_amd64.tar.gz"
      sha256 "a74bacba839222337197559d15f25012cc816cacc77391ff072cc28043d27766"

      define_method(:install) do
        bin.install "social-timeline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcgay/social-timeline/releases/download/v1.0.1/social-timeline_darwin_arm64.tar.gz"
      sha256 "85d336ee8e9908c6b71915aacb7dae119dbe423b0d60856cd19e4f411b8717d7"

      define_method(:install) do
        bin.install "social-timeline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/social-timeline/releases/download/v1.0.1/social-timeline_linux_amd64.tar.gz"
      sha256 "02731a63f7d1d5426753a616b9b992cc9fbb5a982126907bb82ac06998176e0d"
      define_method(:install) do
        bin.install "social-timeline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcgay/social-timeline/releases/download/v1.0.1/social-timeline_linux_arm64.tar.gz"
      sha256 "4d5a62eea85fa5c54c73b47ec058b6a5ed48dab1ce3ba4b81771195227c18b42"
      define_method(:install) do
        bin.install "social-timeline"
      end
    end
  end

  test do
    system "#{bin}/social-timeline", "--version"
  end
end
