# This file was generated by GoReleaser. DO NOT EDIT.
cask "compote" do
  postflight_steps do
    on_macos do
      # binary is unsigned: strip the Gatekeeper quarantine flag
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "compote"], chdir: "."
    end
  end

  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "0fca2b1bc381644aad61e65561128f4f34193ee3143c9cb6091e6036ee071ef2"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "668d889dbe6f45c7204915ba9f0cdab837f80efbe0b98137cee5c79462d69ace"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5eb33b209fcfcaeae0532ddc3ef3b30d726a90a283d84161b5ce6e16258b5674"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "80cf10d1e08c1f16786b144650f3a47d159d58a458f8a174b8f37297560d6d70"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_linux_amd64.tar.gz"
    end
  end

  name "compote"
  desc "Git merge driver that smooths pom.xml version conflicts"
  homepage "https://github.com/jcgay/compote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compote"

  # No zap stanza required

  caveats <<~EOS
    Configure the merge driver:
      git config --global merge.compote.name "Écrase les poms proprement"
      git config --global merge.compote.driver "compote %O %A %B"
    Then bind it to pom.xml, globally for all your repos:
      mkdir -p ~/.config/git
      echo 'pom.xml merge=compote' >> ~/.config/git/attributes
    or per repo, in a committed .gitattributes:
      pom.xml merge=compote
  EOS
end
