# This file was generated by GoReleaser. DO NOT EDIT.
cask "compote" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "1aa91bbfb27d22b2a0fec68a3041ecc712ed6cdb4708a0ca3242252e3395265a"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8e0627d919c9261d854d0323c40a93020825eb8d2a273ba80c6240ff85caad2"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "32bb7f3dea0a7a93586b57f18b72c27ba6c2d3a23b6447802875748957596b2e"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f53501b0d7107c263a883caea59750effec086601e738573051f62412c046d69"
      url "https://github.com/jcgay/compote/releases/download/v#{version}/compote_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compote"
  desc "Git merge driver that smooths pom.xml version conflicts"
  homepage "https://github.com/jcgay/compote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compote"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compote"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure the merge driver:
      git config --global merge.compote.name "Écrase les poms proprement"
      git config --global merge.compote.driver "compote %O %A %B"
    Then bind it to pom.xml, globally for all your repos:
      mkdir -p ~/.config/git
      echo 'pom.xml merge=compote' >> ~/.config/git/attributes
    or per repo, in a committed .gitattributes:
      pom.xml merge=compote
  EOS
end
