# This file was generated by GoReleaser. DO NOT EDIT.
cask "glane" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "f95c60bef1dcd5bbebb2b534e7e27bbabb4244434cb32380bbf0131cc766b550"
      url "https://github.com/jcgay/glane/releases/download/v#{version}/glane_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc1a1e1e67b8796095165d801a70e5df20ddd918c276165ef1bac823c06b4798"
      url "https://github.com/jcgay/glane/releases/download/v#{version}/glane_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b8696a8c20ca506951847c581399d6b8aba1345bd935c92c833a697563ce6c7"
      url "https://github.com/jcgay/glane/releases/download/v#{version}/glane_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b3d81d4d401902860c686f3baf2c066b86ddec9abe9259f2aa7eeb98964d372"
      url "https://github.com/jcgay/glane/releases/download/v#{version}/glane_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glane"
  desc "Full-text and semantic search over your saved tech-watch posts"
  homepage "https://github.com/jcgay/glane"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glane"
  fish_completion "completions/glane.fish"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glane"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To let Claude Code search your tech-watch, register the plugin:
      claude plugin marketplace add jcgay/glane
      claude plugin install glane@glane
  EOS
end
