# This file was generated by GoReleaser. DO NOT EDIT.
cask "parallel-git-repo" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "8871198e738ed7111465c9ed692de0f57341027402b281ce74b4132da1cad057"
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v#{version}/parallel-git-repo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28129899389f7a547cc5fca47edfd798fd162f7c2d00537311149f3670ba96f6"
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v#{version}/parallel-git-repo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dcda36da82996eb6c1756b48f1d6c69e8f7bf6fd097ecb5449b2fb80105b0a53"
      url "https://github.com/jcgay/parallel-git-repo/releases/download/v#{version}/parallel-git-repo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "parallel-git-repo"
  desc "Run command on git repositories in parallel."
  homepage "https://github.com/jcgay/parallel-git-repo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parallel-git-repo"

  # No zap stanza required

end
